version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - DATABASE_URL=postgresql://postgres:071104@db:5432/iot_simulator
    depends_on:
      - db
    volumes:
      - ./:/app
    networks:
      - iot-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=071104
      - POSTGRES_DB=iot_simulator
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - iot-network

volumes:
  postgres_data:

networks:
  iot-network:
    driver: bridge 