services:
  - type: web
    name: iot-simulator-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: API_DEBUG
        value: false
      - key: DATABASE_URL
        sync: false
      - key: API_HOST
        value: 0.0.0.0
      - key: API_PORT
        fromService:
          type: web
          name: iot-simulator-backend
          envVarKey: PORT
