config:
  floors: 10
  max_occupancy: 500
  working_hours:
    start: "08:00"
    end: "20:00"
  timezone: "Europe/Madrid"

room_templates:
  office:
    area: 25
    devices:
      - type: "temperature_sensor"
        config:
          update_interval: 300
      - type: "motion_sensor"
        config:
          sensitivity: 0.8
      - type: "smart_plug"
        count: 2
        config:
          max_power: 2000
      - type: "access_control"
        config:
          authorized_cards: []

  meeting_room:
    area: 40
    devices:
      - type: "temperature_sensor"
      - type: "humidity_sensor"
      - type: "motion_sensor"
      - type: "smart_plug"
        count: 4
      - type: "access_control"

  common_area:
    area: 100
    devices:
      - type: "temperature_sensor"
        count: 2
      - type: "motion_sensor"
        count: 4
      - type: "security_camera"
        count: 2
      - type: "hvac_controller"

  server_room:
    area: 30
    devices:
      - type: "temperature_sensor"
        count: 4
        config:
          update_interval: 60
      - type: "humidity_sensor"
        count: 2
      - type: "power_meter"
        count: 2
      - type: "access_control"
        config:
          security_level: "high"

floors:
  typical_floor:
    rooms:
      offices: 15
      meeting_rooms: 2
      common_areas: 1

  ground_floor:
    rooms:
      offices: 10
      meeting_rooms: 4
      common_areas: 2
      reception: 1

  top_floor:
    rooms:
      offices: 12
      meeting_rooms: 3
      common_areas: 1
      executive_office: 2

traffic_patterns:
  workday:
    morning_peak:
      start: "08:00"
      end: "10:00"
      occupancy_factor: 1.5
    lunch_peak:
      start: "13:00"
      end: "15:00"
      occupancy_factor: 1.2
    evening_peak:
      start: "17:00"
      end: "19:00"
      occupancy_factor: 1.3
  weekend:
    base_occupancy: 0.1 